### ISSUE TITLE
ninja clean; ninja all_unity also builds all

### ISSUE THREAD

**Issue by rodion67** [sakra/cotire#56]
Hello Sascha,
when i create the unity targets, and do a ninja all_unity  the all target is also build.
So actually i build the software twice. Thats not what i want, as this is not faster.
Furthermore unity build with ninja land in a unity subdirectory , so i need to adapt some rules which copy stuff inside the bin dir to be actually able to run my program, how can i easily do this?

Regards,
Gunnar

**Comment by sakra** [comment]
Please check your target dependencies. A unity build may trigger a regular build of another target, if there is a link dependency.

As for the second question. The `unity` output directory was needed for earlier versions of ninja, because ninja would not allow to build rules produce the same output. Newer version of ninja just produce a warning:

    ninja: warning: multiple rules generate example. builds involving this target will not be correct; continuing anyway

If you can tolerate this warning for your builds, you can deactivate the `unity` output directory by setting the variable `COTIRE_UNITY_OUTPUT_DIRECTORY` before including cotire, i.e.:

    set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
    include(cotire)

**Comment by mirkow** [comment]
This seems to happen when the dependee is specified in cmake before the dependency.

e.g. library A and B.
B depends on A.
But your toplevel CmakeLists.txt specify them as:
add_subdirectory(B)
add_subdirectory(A)

Is this solvable?
