### ISSUE TITLE
If target contains excluded files you can't include sources in any other target with PCH.

### ISSUE THREAD

**Issue by tru** [sakra/cotire#59]
This is a strange one that I had to debug for quite a while, in my source we build the same source for several different targets, that worked just fine with cotire until I added a objectivec++ source, because this source get's excluded `${wholeTarget}` get's unset and I get this warning:

```
CMake Error at cmake/cotire.cmake:2523 (message):
  CXX target test2 cotired without precompiled header excluding test.mm.
  Target sources already include a precompiled header for target(s) test1.
  Set target property COTIRE_ENABLE_PRECOMPILED_HEADER to FALSE for targets
  test2, test1 to get a workable build system.
Call Stack (most recent call first):
  cmake/cotire.cmake:2913 (cotire_choose_target_languages)
  cmake/cotire.cmake:3065 (cotire_target)
  CMakeLists.txt:14 (cotire)
```

I am not sure I understand why this happens but it seems wrong to me that an excluded source would lead to the inability to use PCHs.

Here is a minimal CMakeLists.txt that can show the problem:

```cmake
project(cotirebug CXX)
cmake_minimum_required(VERSION 2.8 FATAL_ERROR)

set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake")

include(cotire)

add_executable(test1 main.cpp shared.cpp test.mm)
set_target_properties(test1 PROPERTIES COMPILE_DEFINITIONS "PREPROC=\"test1\"")

add_executable(test2 main.cpp shared.cpp test.mm)
set_target_properties(test2 PROPERTIES COMPILE_DEFINITIONS "PREPROC=\"test2\"")
cotire(test1 test2)
```

If I remove the test.mm from the listing above it works.

I need to invoke CMake with `-DCOTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES=0` to get it to trigger.

Is this intentional or a bug?

**Comment by tru** [comment]
With the following patch everything works just fine. But I am guessing this code is there for a reason.

```diff
diff --git a/CMakeModules/cotire.cmake b/CMakeModules/cotire.cmake
index fd0ad87..6c0b4cf 100644
--- a/CMakeModules/cotire.cmake
+++ b/CMakeModules/cotire.cmake
@@ -2068,7 +2068,7 @@ function (cotire_setup_pch_file_inclusion _language _target _wholeTarget _prefix
                        set_property (SOURCE ${_sourceFiles} APPEND PROPERTY OBJECT_DEPENDS "${_pchFile}")
                endif()
        elseif ("${CMAKE_GENERATOR}" MATCHES "Make|Ninja")
-               if (NOT _wholeTarget)
+               if (0)
                        # for makefile based generator, we force the inclusion of the prefix header for a subset
                        # of the source files, if this is a multi-language target or has excluded files
                        set (_flags "")
```

**Comment by sakra** [comment]
Here's what's going on: Because of the addition of an Objective-C++ file to the target, the target becomes a multi-language target, which is handled differently by cotire.

For single language targets, cotire can force the inclusion of the prefix header by modifying the target's `COMPILE_OPTIONS` flag, which will apply to all source files of the target. For multi-language targets or targets that have excluded files, this is no longer possible, because the modified `COMPILE_OPTIONS` must no affect all source files.

Therefore cotire moves from the target level to the source file level and modifies the `COMPILE_FLAGS` property of selected source files. Unluckily this means that the `COMPILE_FLAGS` will only be correct for one target if the source file is added to multiple targets (as in your example).

Your patch probably works by chance. I'd recommend on generating a static library or a CMake object library for the source files shared by both targets (`main.cpp` and `shared.cpp`) that is linked to both executable targets `test1` and `test2`.

**Comment by tru** [comment]
Thanks for the explanation, I worked around it by using subdirectories for each target.
